### ISSUE TITLE
WARNING: The following packages were previously imported in this runtime On google colab

### ISSUE THREAD

**Issue by IyadElwy** [sizhky/torch_snippets#18] opened 2023-02-26 20:02 UTC
When I try to install torch_snippets using: 
```bash
!pip install torch_snippets
```
I get the following error:

```
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting torch_snippets
  Downloading torch_snippets-0.499.19-py3-none-any.whl (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.8/54.8 KB 4.5 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (1.22.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (4.64.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (1.3.5)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (4.5.0)
Collecting rich
  Downloading rich-13.3.1-py3-none-any.whl (239 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 239.0/239.0 KB 29.2 MB/s eta 0:00:00
Collecting loguru
  Downloading loguru-0.6.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 KB 9.1 MB/s eta 0:00:00
Requirement already satisfied: fastcore in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (1.5.28)
Requirement already satisfied: altair in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (4.2.2)
Requirement already satisfied: srsly in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (2.4.5)
Requirement already satisfied: nltk in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (3.7)
Collecting python-Levenshtein
  Downloading python_Levenshtein-0.20.9-py3-none-any.whl (9.4 kB)
Collecting lovely-tensors
  Downloading lovely_tensors-0.1.14-py3-none-any.whl (16 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (1.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (7.1.2)
Collecting jsonlines
  Downloading jsonlines-3.1.0-py3-none-any.whl (8.6 kB)
Collecting pre-commit
  Downloading pre_commit-3.1.0-py2.py3-none-any.whl (202 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.2/202.2 KB 22.6 MB/s eta 0:00:00
Requirement already satisfied: ipython in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (7.9.0)
Requirement already satisfied: imgaug>=0.4.0 in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (0.4.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (6.0)
Collecting typing
  Downloading typing-3.7.4.3.tar.gz (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.6/78.6 KB 11.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: matplotlib in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (3.5.3)
Collecting xmltodict
  Downloading xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)
Requirement already satisfied: confection in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (0.0.4)
Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: wasabi in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (0.10.1)
Requirement already satisfied: dill in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (0.3.6)
Requirement already satisfied: pydantic in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (1.10.5)
Requirement already satisfied: catalogue in /usr/local/lib/python3.8/dist-packages (from torch_snippets) (2.0.8)
Requirement already satisfied: scikit-image>=0.14.2 in /usr/local/lib/python3.8/dist-packages (from imgaug>=0.4.0->torch_snippets) (0.18.3)
Requirement already satisfied: imageio in /usr/local/lib/python3.8/dist-packages (from imgaug>=0.4.0->torch_snippets) (2.9.0)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.8/dist-packages (from imgaug>=0.4.0->torch_snippets) (4.6.0.66)
Requirement already satisfied: Shapely in /usr/local/lib/python3.8/dist-packages (from imgaug>=0.4.0->torch_snippets) (2.0.1)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from imgaug>=0.4.0->torch_snippets) (1.15.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.8/dist-packages (from imgaug>=0.4.0->torch_snippets) (1.7.3)
Requirement already satisfied: toolz in /usr/local/lib/python3.8/dist-packages (from altair->torch_snippets) (0.12.0)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.8/dist-packages (from altair->torch_snippets) (4.3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.8/dist-packages (from altair->torch_snippets) (2.11.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.8/dist-packages (from altair->torch_snippets) (0.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas->torch_snippets) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas->torch_snippets) (2022.7.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from fastcore->torch_snippets) (23.0)
Requirement already satisfied: pip in /usr/local/lib/python3.8/dist-packages (from fastcore->torch_snippets) (22.0.4)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.8/dist-packages (from ipython->torch_snippets) (5.7.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.8/dist-packages (from ipython->torch_snippets) (4.4.2)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.8/dist-packages (from ipython->torch_snippets) (57.4.0)
Requirement already satisfied: pexpect in /usr/local/lib/python3.8/dist-packages (from ipython->torch_snippets) (4.8.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.8/dist-packages (from ipython->torch_snippets) (0.7.5)
Collecting jedi>=0.10
  Downloading jedi-0.18.2-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 80.9 MB/s eta 0:00:00
Requirement already satisfied: backcall in /usr/local/lib/python3.8/dist-packages (from ipython->torch_snippets) (0.2.0)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from ipython->torch_snippets) (2.0.10)
Requirement already satisfied: pygments in /usr/local/lib/python3.8/dist-packages (from ipython->torch_snippets) (2.6.1)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.8/dist-packages (from jsonlines->torch_snippets) (22.2.0)
Collecting lovely-numpy>=0.2.8
  Downloading lovely_numpy-0.2.8-py3-none-any.whl (23 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.8/dist-packages (from lovely-tensors->torch_snippets) (1.13.1+cu116)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->torch_snippets) (1.4.4)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib->torch_snippets) (4.38.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib->torch_snippets) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->torch_snippets) (3.0.9)
Requirement already satisfied: click in /usr/local/lib/python3.8/dist-packages (from nltk->torch_snippets) (7.1.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.8/dist-packages (from nltk->torch_snippets) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.8/dist-packages (from nltk->torch_snippets) (2022.6.2)
Collecting identify>=1.0.0
  Downloading identify-2.5.18-py2.py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.8/98.8 KB 12.5 MB/s eta 0:00:00
Collecting cfgv>=2.0.0
  Downloading cfgv-3.3.1-py2.py3-none-any.whl (7.3 kB)
Collecting virtualenv>=20.10.0
  Downloading virtualenv-20.19.0-py3-none-any.whl (8.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 105.0 MB/s eta 0:00:00
Collecting nodeenv>=0.11.1
  Downloading nodeenv-1.7.0-py2.py3-none-any.whl (21 kB)
Collecting Levenshtein==0.20.9
  Downloading Levenshtein-0.20.9-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (174 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.0/174.0 KB 24.7 MB/s eta 0:00:00
Collecting rapidfuzz<3.0.0,>=2.3.0
  Downloading rapidfuzz-2.13.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 104.9 MB/s eta 0:00:00
Collecting pygments
  Downloading Pygments-2.14.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 81.5 MB/s eta 0:00:00
Collecting markdown-it-py<3.0.0,>=2.1.0
  Downloading markdown_it_py-2.2.0-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.5/84.5 KB 12.5 MB/s eta 0:00:00
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn->torch_snippets) (3.1.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.8/dist-packages (from jedi>=0.10->ipython->torch_snippets) (0.8.3)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.8/dist-packages (from jsonschema>=3.0->altair->torch_snippets) (0.19.3)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.8/dist-packages (from jsonschema>=3.0->altair->torch_snippets) (5.12.0)
Collecting mdurl~=0.1
  Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.8/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython->torch_snippets) (0.2.6)
Requirement already satisfied: networkx>=2.0 in /usr/local/lib/python3.8/dist-packages (from scikit-image>=0.14.2->imgaug>=0.4.0->torch_snippets) (3.0)
Requirement already satisfied: PyWavelets>=1.1.1 in /usr/local/lib/python3.8/dist-packages (from scikit-image>=0.14.2->imgaug>=0.4.0->torch_snippets) (1.4.1)
Requirement already satisfied: tifffile>=2019.7.26 in /usr/local/lib/python3.8/dist-packages (from scikit-image>=0.14.2->imgaug>=0.4.0->torch_snippets) (2023.2.3)
Requirement already satisfied: platformdirs<4,>=2.4 in /usr/local/lib/python3.8/dist-packages (from virtualenv>=20.10.0->pre-commit->torch_snippets) (3.0.0)
Collecting distlib<1,>=0.3.6
  Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.5/468.5 KB 50.4 MB/s eta 0:00:00
Requirement already satisfied: filelock<4,>=3.4.1 in /usr/local/lib/python3.8/dist-packages (from virtualenv>=20.10.0->pre-commit->torch_snippets) (3.9.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.8/dist-packages (from jinja2->altair->torch_snippets) (2.0.1)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.8/dist-packages (from pexpect->ipython->torch_snippets) (0.7.0)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.8/dist-packages (from importlib-resources>=1.4.0->jsonschema>=3.0->altair->torch_snippets) (3.14.0)
Building wheels for collected packages: typing
  Building wheel for typing (setup.py) ... done
  Created wheel for typing: filename=typing-3.7.4.3-py3-none-any.whl size=26323 sha256=08293018828d6cfa19c86a7b299a010f18b29815b913657c44bee4c98a5a7f60
  Stored in directory: /root/.cache/pip/wheels/5e/5d/01/3083e091b57809dad979ea543def62d9d878950e3e74f0c930
Successfully built typing
Installing collected packages: fuzzywuzzy, distlib, xmltodict, virtualenv, typing, rapidfuzz, pygments, nodeenv, mdurl, loguru, jsonlines, jedi, identify, cfgv, pre-commit, markdown-it-py, Levenshtein, rich, python-Levenshtein, lovely-numpy, lovely-tensors, torch_snippets
  Attempting uninstall: pygments
    Found existing installation: Pygments 2.6.1
    Uninstalling Pygments-2.6.1:
      Successfully uninstalled Pygments-2.6.1
Successfully installed Levenshtein-0.20.9 cfgv-3.3.1 distlib-0.3.6 fuzzywuzzy-0.18.0 identify-2.5.18 jedi-0.18.2 jsonlines-3.1.0 loguru-0.6.0 lovely-numpy-0.2.8 lovely-tensors-0.1.14 markdown-it-py-2.2.0 mdurl-0.1.2 nodeenv-1.7.0 pre-commit-3.1.0 pygments-2.14.0 python-Levenshtein-0.20.9 rapidfuzz-2.13.7 rich-13.3.1 torch_snippets-0.499.19 typing-3.7.4.3 virtualenv-20.19.0 xmltodict-0.13.0
WARNING: The following packages were previously imported in this runtime:
  [pygments,typing]
You must restart the runtime in order to use newly installed versions.
```

Here is a screenshot of the same error:
![chapter_7-ipynb-Colaboratory](https://user-images.githubusercontent.com/83036619/221433978-cc2f7bd3-219e-4f74-9581-234e9d9aa1c9.png)

I ignored the error and tried to import torch_snippets like so:
```python
from torch_snippets import *
```
but then I got:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-3-3c519ad45397>](https://localhost:8080/#) in <module>
----> 1 from torch_snippets import *

1 frames
[/usr/local/lib/python3.8/dist-packages/torch_snippets/pdf_loader.py](https://localhost:8080/#) in <module>
      6 # %% ../nbs/pdf.ipynb 2
      7 from .loader import np, subplots, show, resize, L, Image
----> 8 import fitz
      9 
     10 # %% ../nbs/pdf.ipynb 3

ModuleNotFoundError: No module named 'fitz'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by javadvahid** [comment] 2023-12-27 09:58
I don't know the problem is solved or not but I finally decided to implement the functions I needed, using the source codes available. probably the best thing to do.
thanks for the effort

**Comment by sizhky** [comment] 2024-03-08 13:09
I think they are all solved.. closing the issue

**Closed by sizhky** 2024-03-08 13:09 UTC
